name: 'Setup Linux Environment'
description: 'Builds Docker image and restores caches'

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ci/docker/linux
        push: true
        load: false
        tags: |
          ghcr.io/codethinki/cth:linux-latest
          cth-linux:latest
        cache-from: type=registry,ref=ghcr.io/codethinki/cth:linux-latest
        cache-to: type=registry,ref=ghcr.io/codethinki/cth:linux-latest,mode=max

    - name: Create BuildCache Directory
      shell: bash
      run: mkdir -p .buildcache

    - name: Restore BuildCache directory
      uses: actions/cache@v4
      with:
        path: .buildcache
        key: buildcache-linux-${{ github.sha }}
        restore-keys: |
          buildcache-linux-

    - name: Export GitHub Actions Cache Environment
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
