name: 'Prepare Windows Environment'
description: 'Clones and Caches Vcpkg and Pip dependencies'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Cache Pip
      uses: actions/cache@v4
      with:
        path: ~\AppData\Local\pip\Cache
        key: pip-windows-${{ hashFiles('.github/requirements.txt') }}
        restore-keys: |
            pip-windows-

    - name: Install Runtime Tools
      shell: pwsh
      run: |
        pip install --upgrade -r .github/requirements.txt

    - name: Restore Custom Vcpkg
      id: restore-vcpkg
      uses: actions/cache/restore@v4
      with:
        path: c:\vcpkg-custom
        key: vcpkg-custom-repo-windows-restore-search
        restore-keys: |
            vcpkg-custom-repo-windows-

    - name: Setup Vcpkg (Clone/Update)
      shell: pwsh
      run: |
        $vcpkgPath = "c:\vcpkg-custom"
        if (!(Test-Path "$vcpkgPath\.git")) {
            Write-Host "Cloning vcpkg..."
            git clone https://github.com/microsoft/vcpkg.git $vcpkgPath
        } else {
            Write-Host "Fetching vcpkg updates..."
            Push-Location $vcpkgPath
            git fetch origin master
            git pull origin master
            Pop-Location
        }
        
        Push-Location $vcpkgPath
        $sha = git rev-parse HEAD
        Pop-Location
        "VCPKG_SHA=$sha" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

        & "$vcpkgPath\bootstrap-vcpkg.bat" -disableMetrics

    - name: Save Custom Vcpkg (New State)
      if: steps.restore-vcpkg.outputs.cache-matched-key != format('vcpkg-custom-repo-windows-{0}', env.VCPKG_SHA)
      uses: actions/cache/save@v4
      with:
        path: c:\vcpkg-custom
        key: vcpkg-custom-repo-windows-${{ env.VCPKG_SHA }}

    - name: Restore BuildCache Tool
      id: restore-buildcache-tool
      uses: actions/cache/restore@v4
      with:
        path: c:\buildcache
        key: buildcache-tool-windows-v0.31.7

    - name: Download BuildCache Tool
      if: steps.restore-buildcache-tool.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://gitlab.com/bits-n-bites/buildcache/-/releases/v0.31.7/downloads/buildcache-windows.zip" -OutFile "buildcache.zip"
        Expand-Archive buildcache.zip -DestinationPath c:\buildcache

    - name: Save BuildCache Tool
      if: steps.restore-buildcache-tool.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: c:\buildcache
        key: buildcache-tool-windows-v0.31.7
