name: 'Setup Windows Environment'
description: 'Sets up Vcpkg, BuildCache, and restores caches for Windows'
inputs:
  compiler:
    description: 'Compiler suffix for cache key (msvc or clang)'
    required: true

runs:
  using: "composite"
  steps:
    - uses: ilammy/msvc-dev-cmd@v1

    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Cache Pip
      uses: actions/cache@v4
      with:
        path: ~\AppData\Local\pip\Cache
        key: pip-windows-${{ hashFiles('.github/requirements.txt') }}
        restore-keys: |
            pip-windows-

    - name: Install CMake & Ninja (Pip)
      shell: pwsh
      run: |
        pip install --upgrade -r .github/requirements.txt
        $pythonScriptPath = (python -c "import sysconfig; print(sysconfig.get_path('scripts'))")
        echo "$pythonScriptPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Restore BuildCache directory
      uses: actions/cache@v4
      with:
        path: ~/.buildcache
        key: buildcache-windows-${{ inputs.compiler }}-${{ github.sha }}
        restore-keys: |
          buildcache-windows-${{ inputs.compiler }}-

    - name: Setup Vcpkg (Latest)
      shell: pwsh
      run: |
        if (!(Test-Path "c:\vcpkg-custom\.git")) {
            git clone https://github.com/microsoft/vcpkg.git c:\vcpkg-custom
        }
        & "c:\vcpkg-custom\bootstrap-vcpkg.bat" -disableMetrics
        echo "VCPKG_ROOT=c:\vcpkg-custom" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "c:\vcpkg-custom" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install BuildCache
      shell: pwsh
      run: |
        if (!(Test-Path "c:\buildcache\buildcache\bin\buildcache.exe")) {
          Invoke-WebRequest -Uri "https://gitlab.com/bits-n-bites/buildcache/-/releases/v0.31.7/downloads/buildcache-windows.zip" -OutFile "buildcache.zip"
          Expand-Archive buildcache.zip -DestinationPath c:\buildcache
        }
        echo "c:\buildcache\buildcache\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Enable GitHub Actions Cache for Vcpkg
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
