name: 'Setup Windows Environment'
description: 'Sets up Vcpkg, BuildCache, and restores caches for Windows'
inputs:
  compiler:
    description: 'Compiler suffix for cache key (msvc or clang)'
    required: true

runs:
  using: "composite"
  steps:
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Setup Vcpkg Env
      shell: pwsh
      run: |
        echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Install Latest CMake
      shell: pwsh
      run: |
        if (!(Test-Path "c:\cmake\bin\cmake.exe")) {
          $latest = (Invoke-RestMethod -Uri "https://api.github.com/repos/Kitware/CMake/releases/latest").tag_name
          $version = $latest -replace "v", ""
          $url = "https://github.com/Kitware/CMake/releases/download/$latest/cmake-$version-windows-x86_64.zip"
          Write-Host "Downloading CMake $version from $url"
          Invoke-WebRequest -Uri $url -OutFile "cmake.zip"
          Expand-Archive cmake.zip -DestinationPath c:\cmake_temp
          Move-Item c:\cmake_temp\cmake-*-windows-x86_64 c:\cmake
          Remove-Item cmake.zip
          Remove-Item c:\cmake_temp -Recurse
        }
        echo "c:\cmake\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install BuildCache
      shell: pwsh
      run: |
        if (!(Test-Path "c:\buildcache\buildcache\bin\buildcache.exe")) {
          Invoke-WebRequest -Uri "https://gitlab.com/bits-n-bites/buildcache/-/releases/v0.31.7/downloads/buildcache-windows.zip" -OutFile "buildcache.zip"
          Expand-Archive buildcache.zip -DestinationPath c:\buildcache
        }
        echo "c:\buildcache\buildcache\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Restore BuildCache directory
      uses: actions/cache@v4
      with:
        path: |
           ~/.buildcache
           c:/cmake
        key: buildcache-windows-${{ inputs.compiler }}-${{ github.sha }}
        restore-keys: |
          buildcache-windows-${{ inputs.compiler }}-

    - name: Enable GitHub Actions Cache for Vcpkg
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
