name: 'Setup Windows Environment'
description: 'Sets up Vcpkg, BuildCache, and restores caches for Windows'
inputs:
  compiler:
    description: 'Compiler suffix for cache key (msvc or clang)'
    required: true

runs:
  using: "composite"
  steps:
    - uses: ilammy/msvc-dev-cmd@v1

    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Cache Pip
      uses: actions/cache@v4
      with:
        path: ~\AppData\Local\pip\Cache
        key: pip-windows-${{ hashFiles('.github/requirements.txt') }}
        restore-keys: |
            pip-windows-

    - name: Configure VCPKG_DOWNLOADS
      shell: pwsh
      run: |
        echo "VCPKG_DOWNLOADS=$HOME\AppData\Local\vcpkg\downloads" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        New-Item -ItemType Directory -Force -Path "$HOME\AppData\Local\vcpkg\downloads"

    - name: Install CMake & Ninja (Pip)
      shell: pwsh
      run: |
        pip install --upgrade -r .github/requirements.txt

    - name: Check CMake Version
      shell: pwsh
      run: cmake --version


    - name: Restore BuildCache directory
      uses: actions/cache@v4
      with:
        path: ~/.buildcache
        key: buildcache-windows-${{ inputs.compiler }}-${{ github.sha }}
        restore-keys: |
          buildcache-windows-${{ inputs.compiler }}-

    - name: Restore Custom Vcpkg
      id: restore-vcpkg
      uses: actions/cache/restore@v4
      with:
        path: c:\vcpkg-custom
        key: vcpkg-custom-repo-windows-restore-search
        restore-keys: |
            vcpkg-custom-repo-windows-

    - name: Setup Vcpkg (Clone/Update)
      shell: pwsh
      run: |
        $vcpkgPath = "c:\vcpkg-custom"
        if (!(Test-Path "$vcpkgPath\.git")) {
            Write-Host "Cloning vcpkg..."
            git clone https://github.com/microsoft/vcpkg.git $vcpkgPath
        } else {
            Write-Host "Fetching vcpkg updates..."
            Push-Location $vcpkgPath
            git fetch origin master
            git pull origin master
            Pop-Location
        }
        
        Push-Location $vcpkgPath
        $sha = git rev-parse HEAD
        Pop-Location
        "VCPKG_SHA=$sha" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

        & "$vcpkgPath\bootstrap-vcpkg.bat" -disableMetrics
        
        echo "VCPKG_ROOT=$vcpkgPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "$vcpkgPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Save Custom Vcpkg (New State)
      if: steps.restore-vcpkg.outputs.cache-matched-key != format('vcpkg-custom-repo-windows-{0}', env.VCPKG_SHA)
      uses: actions/cache/save@v4
      with:
        path: c:\vcpkg-custom
        key: vcpkg-custom-repo-windows-${{ env.VCPKG_SHA }}

    - name: Install BuildCache
      shell: pwsh
      run: |
        if (!(Test-Path "c:\buildcache\buildcache\bin\buildcache.exe")) {
          Invoke-WebRequest -Uri "https://gitlab.com/bits-n-bites/buildcache/-/releases/v0.31.7/downloads/buildcache-windows.zip" -OutFile "buildcache.zip"
          Expand-Archive buildcache.zip -DestinationPath c:\buildcache
        }
        echo "c:\buildcache\buildcache\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Enable GitHub Actions Cache for Vcpkg
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
