name: 'Setup Windows Environment'
description: 'Restores Vcpkg, BuildCache etc.'
inputs:
  compiler:
    description: 'Compiler suffix for cache key (msvc or clang)'
    required: true

runs:
  using: "composite"
  steps:
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Restore BuildCache directory
      uses: actions/cache@v4
      with:
        path: ~/.buildcache
        key: buildcache-windows-${{ inputs.compiler }}-${{ github.sha }}
        restore-keys: |
          buildcache-windows-${{ inputs.compiler }}-

    - name: Restore Custom Vcpkg
      id: restore-vcpkg
      uses: actions/cache/restore@v4
      with:
        path: c:\vcpkg-custom
        key: vcpkg-custom-repo-windows-restore-search # Restore latest available
        restore-keys: |
            vcpkg-custom-repo-windows-

    - name: Setup Vcpkg Environment
      shell: pwsh
      run: |
        $vcpkgPath = "c:\vcpkg-custom"
        if (!(Test-Path "$vcpkgPath\.git")) {
           Write-Error "Vcpkg not found! Did prepare-windows run?"
           exit 1
        }
        
        echo "VCPKG_ROOT=$vcpkgPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "$vcpkgPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Restore BuildCache Tool
      id: restore-buildcache-tool
      uses: actions/cache/restore@v4
      with:
        path: c:\buildcache
        key: buildcache-tool-windows-v0.31.7

    - name: Install BuildCache
      shell: pwsh
      run: |
        if (!(Test-Path "c:\buildcache\buildcache\bin\buildcache.exe")) {
          Invoke-WebRequest -Uri "https://gitlab.com/bits-n-bites/buildcache/-/releases/v0.31.7/downloads/buildcache-windows.zip" -OutFile "buildcache.zip"
          Expand-Archive buildcache.zip -DestinationPath c:\buildcache
        }
        echo "c:\buildcache\buildcache\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Enable GitHub Actions Cache for Vcpkg
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
