function(set_compiler_specifics)
if(MSVC)
  set(CMAKE_MSVC_EXCEPTIONS ON)
  add_compile_options(/MP /utf-8)
  add_compile_options("$<$<C_COMPILER_ID:MSVC>:/utf-8>")
  add_compile_options("$<$<CXX_COMPILER_ID:MSVC>:/utf-8>")
else()
  add_compile_options(-fexceptions)
endif()
endfunction()