function(target_install_include_directories TARGET)
    set(CURRENT_MODE "PUBLIC")
    set(PUBLIC_DIRS "")
    set(PRIVATE_DIRS "")
    set(INTERFACE_DIRS "")

    foreach(ARG ${ARGN})
        if("${ARG}" STREQUAL "PUBLIC")
            set(CURRENT_MODE "PUBLIC")
        elseif("${ARG}" STREQUAL "PRIVATE")
            set(CURRENT_MODE "PRIVATE")
        elseif("${ARG}" STREQUAL "INTERFACE")
            set(CURRENT_MODE "INTERFACE")
        else()
            list(APPEND ${CURRENT_MODE}_DIRS ${ARG})
        endif()
    endforeach()

    if(PUBLIC_DIRS)
        set(PROCESSED_PUBLIC_DIRS "")
        foreach(DIR ${PUBLIC_DIRS})
            list(APPEND PROCESSED_PUBLIC_DIRS "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/${DIR}>")
            list(APPEND PROCESSED_PUBLIC_DIRS "$<INSTALL_INTERFACE:${DIR}>")
        endforeach()
        target_include_directories(${TARGET} PUBLIC ${PROCESSED_PUBLIC_DIRS})
    endif()

    if(PRIVATE_DIRS)
        set(PROCESSED_PRIVATE_DIRS "")
        foreach(DIR ${PRIVATE_DIRS})
            # Private includes are ONLY for the build tree. They are not installed.
            list(APPEND PROCESSED_PRIVATE_DIRS "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/${DIR}>")
        endforeach()
        target_include_directories(${TARGET} PRIVATE ${PROCESSED_PRIVATE_DIRS})
    endif()

    # --- Process INTERFACE directories ---
    if(INTERFACE_DIRS)
        set(PROCESSED_INTERFACE_DIRS "")
        foreach(DIR ${INTERFACE_DIRS})
            list(APPEND PROCESSED_INTERFACE_DIRS "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/${DIR}>")
            list(APPEND PROCESSED_INTERFACE_DIRS "$<INSTALL_INTERFACE:${DIR}>")
        endforeach()
        target_include_directories(${TARGET} INTERFACE ${PROCESSED_INTERFACE_DIRS})
    endif()

endfunction()